Repository tobiturner/to-do-list, pull requests merged in 2022-10, with the labels that each got.

#16 fixed index and validation
  card.html
  index.html
Labels: Improvement

#20 Add pop up function to the main-page
  index.html
  resources/style.css
  script.js
Labels: Improvement

#18 Added the google documentation to the readme
  README.md
  archive
Labels: documentation

#26 Layout update
  index.html
  resources/style.css
Labels: Improvement

#28 Responsive website
  index.html
  resources/style.css
  script.js
Labels: bug

#27 Added new fonts, changed other fonts, adjusted navbar size
  index.html
  resources/style.css
Labels: enhancement

#31 fixed logo in mobile, added space between title edges, centered card in mobile
  resources/style.css
Labels: bug
